# Gary×Taleb Trading System - Kubernetes Namespaces
# Namespace definitions for environment separation

apiVersion: v1
kind: Namespace
metadata:
  name: gary-taleb-production
  labels:
    name: gary-taleb-production
    environment: production
    tier: trading-platform
    compliance: defense-industry
  annotations:
    description: "Gary×Taleb Trading System - Production Environment"
    contact: "platform-team@gary-taleb.com"
    compliance: "NASA POT10, SOC2 Type II"
---
apiVersion: v1
kind: Namespace
metadata:
  name: gary-taleb-staging
  labels:
    name: gary-taleb-staging
    environment: staging
    tier: trading-platform
  annotations:
    description: "Gary×Taleb Trading System - Staging Environment"
    contact: "platform-team@gary-taleb.com"
---
apiVersion: v1
kind: Namespace
metadata:
  name: gary-taleb-development
  labels:
    name: gary-taleb-development
    environment: development
    tier: trading-platform
  annotations:
    description: "Gary×Taleb Trading System - Development Environment"
    contact: "platform-team@gary-taleb.com"
---
apiVersion: v1
kind: Namespace
metadata:
  name: gary-taleb-monitoring
  labels:
    name: gary-taleb-monitoring
    environment: shared
    tier: observability
  annotations:
    description: "Gary×Taleb Trading System - Monitoring and Observability"
    contact: "platform-team@gary-taleb.com"
---
# Resource Quotas for Production
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: gary-taleb-production
spec:
  hard:
    requests.cpu: "400"
    requests.memory: 1600Gi
    requests.nvidia.com/gpu: "16"
    limits.cpu: "500"
    limits.memory: 2000Gi
    limits.nvidia.com/gpu: "20"
    persistentvolumeclaims: "100"
    requests.storage: 50Ti
    count/deployments.apps: "50"
    count/services: "50"
    count/secrets: "100"
    count/configmaps: "100"
---
# Resource Quotas for Staging
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: gary-taleb-staging
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 400Gi
    requests.nvidia.com/gpu: "4"
    limits.cpu: "150"
    limits.memory: 600Gi
    limits.nvidia.com/gpu: "6"
    persistentvolumeclaims: "50"
    requests.storage: 10Ti
    count/deployments.apps: "25"
    count/services: "25"
---
# Resource Quotas for Development
apiVersion: v1
kind: ResourceQuota
metadata:
  name: development-quota
  namespace: gary-taleb-development
spec:
  hard:
    requests.cpu: "50"
    requests.memory: 200Gi
    requests.nvidia.com/gpu: "2"
    limits.cpu: "75"
    limits.memory: 300Gi
    limits.nvidia.com/gpu: "4"
    persistentvolumeclaims: "25"
    requests.storage: 5Ti
    count/deployments.apps: "15"
    count/services: "15"
---
# Network Policies for Production Security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production-network-policy
  namespace: gary-taleb-production
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: gary-taleb-monitoring
    - namespaceSelector:
        matchLabels:
          name: gary-taleb-production
    - podSelector:
        matchLabels:
          tier: core
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: gary-taleb-production
  - to:
    - namespaceSelector:
        matchLabels:
          name: gary-taleb-monitoring
  - to: []  # Allow external egress for broker APIs
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
---
# Limit Ranges for Resource Control
apiVersion: v1
kind: LimitRange
metadata:
  name: production-limits
  namespace: gary-taleb-production
spec:
  limits:
  - type: Container
    default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: "0.5"
      memory: 1Gi
    min:
      cpu: "0.1"
      memory: 128Mi
    max:
      cpu: "32"
      memory: 128Gi
  - type: PersistentVolumeClaim
    min:
      storage: 1Gi
    max:
      storage: 10Ti
---
apiVersion: v1
kind: LimitRange
metadata:
  name: staging-limits
  namespace: gary-taleb-staging
spec:
  limits:
  - type: Container
    default:
      cpu: "1"
      memory: 2Gi
    defaultRequest:
      cpu: "0.25"
      memory: 512Mi
    min:
      cpu: "0.1"
      memory: 128Mi
    max:
      cpu: "16"
      memory: 64Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: development-limits
  namespace: gary-taleb-development
spec:
  limits:
  - type: Container
    default:
      cpu: "0.5"
      memory: 1Gi
    defaultRequest:
      cpu: "0.1"
      memory: 256Mi
    min:
      cpu: "0.05"
      memory: 64Mi
    max:
      cpu: "8"
      memory: 32Gi