# Enterprise Configuration for SPEK Enhanced Development Platform
# Six Sigma and Quality Management Settings

sixSigma:
  targetSigma: 4.0
  sigmaShift: 1.5
  performanceThreshold: 1.2  # <1.2% overhead
  maxExecutionTime: 5000     # 5 seconds max
  maxMemoryUsage: 100        # 100MB max

quality:
  targetSigma: 4.0
  sigmaShift: 1.5
  nasaPOT10Target: 95        # 95%+ compliance
  auditTrailEnabled: true

performance:
  maxOverhead: 1.2           # 1.2% maximum overhead
  maxExecutionTime: 5000     # 5 seconds
  maxMemoryUsage: 100        # 100MB
  monitoringEnabled: true

compliance:
  nasaPOT10: 95              # NASA POT10 compliance target
  auditTrailEnabled: true
  evidenceRequirements:
    ctqCalculations: true
    spcCharts: true
    dpmoAnalysis: true
    theaterDetection: true

artifacts:
  outputPath: ".claude/.artifacts/sixsigma/"
  reportFormats:
    - executive
    - detailed
    - technical
    - dashboard

theater:
  enableDetection: true
  riskThresholds:
    low: 0.3
    medium: 0.6
    high: 0.8