# Enterprise Feature Flags Configuration
# Environment-specific feature toggles with gradual rollout support

# Global Configuration
global:
  environment: "${NODE_ENV:-development}"
  cache_timeout: 5000  # 5 seconds
  evaluation_timeout: 100  # 100ms
  circuit_breaker_threshold: 0.95
  max_audit_entries: 10000

# Development Environment Flags
development:
  # Development and Testing Features
  debug_mode:
    enabled: true
    description: "Enable debug logging and development tools"
    rollout_strategy: "boolean"
    environments:
      development: true
      staging: true
      production: false

  feature_flag_ui:
    enabled: true
    description: "Feature flag management UI for developers"
    rollout_strategy: "boolean"
    environments:
      development: true
      staging: true
      production: false

# CI/CD Integration Flags
ci_cd:
  # Quality Gate Controls
  strict_quality_gates:
    enabled: true
    description: "Enforce strict quality gate thresholds"
    rollout_strategy: "boolean"
    environments:
      development: false
      staging: true
      production: true
    conditions:
      - field: "branch"
        operator: "in"
        value: ["main", "master", "release/*"]

  parallel_test_execution:
    enabled: true
    description: "Enable parallel test execution in CI/CD"
    rollout_strategy: "percentage"
    rollout_percentage: 80
    environments:
      development: true
      staging: true
      production: false

  automated_security_scanning:
    enabled: true
    description: "Automatic security vulnerability scanning"
    rollout_strategy: "boolean"
    environments:
      development: true
      staging: true
      production: true

  deployment_approval_gates:
    enabled: true
    description: "Require manual approval for production deployments"
    rollout_strategy: "boolean"
    environments:
      production: true
    conditions:
      - field: "target_environment"
        operator: "equals"
        value: "production"

# Performance and Monitoring Flags
performance:
  real_time_performance_monitoring:
    enabled: true
    description: "Real-time application performance monitoring"
    rollout_strategy: "percentage"
    rollout_percentage: 100
    environments:
      development: true
      staging: true
      production: true

  detailed_metrics_collection:
    enabled: true
    description: "Collect detailed application metrics"
    rollout_strategy: "percentage"
    rollout_percentage: 90
    environments:
      staging: true
      production: true
    metadata:
      sampling_rate: 0.1
      retention_days: 30

  circuit_breaker_monitoring:
    enabled: true
    description: "Monitor and report circuit breaker states"
    rollout_strategy: "boolean"
    environments:
      staging: true
      production: true

# Compliance and Security Flags
compliance:
  dfars_compliance_checks:
    enabled: true
    description: "DFARS compliance validation in CI/CD"
    rollout_strategy: "boolean"
    environments:
      production: true
    conditions:
      - field: "project_type"
        operator: "in"
        value: ["defense", "government", "enterprise"]

  audit_logging:
    enabled: true
    description: "Comprehensive audit logging"
    rollout_strategy: "boolean"
    environments:
      staging: true
      production: true

  data_encryption:
    enabled: true
    description: "Enable data encryption at rest and in transit"
    rollout_strategy: "boolean"
    environments:
      production: true

  pii_detection:
    enabled: true
    description: "Automatic PII detection and masking"
    rollout_strategy: "percentage"
    rollout_percentage: 75
    environments:
      staging: true
      production: true

# Feature Rollout Flags
features:
  # API Features
  api_v2:
    enabled: false
    description: "Enable API v2 endpoints"
    rollout_strategy: "percentage"
    rollout_percentage: 10
    environments:
      development: true
      staging: false
      production: false
    variants:
      - key: "v2_full"
        value: { version: "2.0", features: ["all"] }
        weight: 50
      - key: "v2_limited"
        value: { version: "2.0", features: ["basic"] }
        weight: 50

  enhanced_analytics:
    enabled: false
    description: "Enhanced analytics and reporting"
    rollout_strategy: "user"
    environments:
      development: true
      staging: true
      production: false
    metadata:
      user_list: ["admin", "analytics_team"]

  machine_learning_features:
    enabled: false
    description: "AI/ML powered features"
    rollout_strategy: "percentage"
    rollout_percentage: 5
    environments:
      development: true
      staging: false
      production: false

# Infrastructure Flags
infrastructure:
  database_read_replicas:
    enabled: true
    description: "Use database read replicas for queries"
    rollout_strategy: "percentage"
    rollout_percentage: 80
    environments:
      staging: true
      production: true

  caching_layer:
    enabled: true
    description: "Enable Redis caching layer"
    rollout_strategy: "boolean"
    environments:
      staging: true
      production: true

  cdn_optimization:
    enabled: true
    description: "Enable CDN for static assets"
    rollout_strategy: "boolean"
    environments:
      production: true

# A/B Testing Flags
experiments:
  checkout_flow_v2:
    enabled: false
    description: "A/B test new checkout flow"
    rollout_strategy: "variant"
    rollout_percentage: 20
    environments:
      staging: true
      production: false
    variants:
      - key: "single_page"
        value: { flow_type: "single_page", steps: 1 }
        weight: 50
      - key: "multi_step"
        value: { flow_type: "multi_step", steps: 3 }
        weight: 50
    conditions:
      - field: "user_segment"
        operator: "in"
        value: ["premium", "enterprise"]

  ui_theme:
    enabled: false
    description: "Test different UI themes"
    rollout_strategy: "variant"
    rollout_percentage: 30
    environments:
      development: true
      staging: true
    variants:
      - key: "light"
        value: { theme: "light", colors: "default" }
        weight: 40
      - key: "dark"
        value: { theme: "dark", colors: "inverted" }
        weight: 40
      - key: "auto"
        value: { theme: "auto", colors: "system" }
        weight: 20

# Emergency Controls
emergency:
  kill_switch:
    enabled: false
    description: "Emergency kill switch for new features"
    rollout_strategy: "boolean"
    environments:
      production: false
    metadata:
      emergency_contact: "ops-team@company.com"
      escalation_time: 300  # 5 minutes

  maintenance_mode:
    enabled: false
    description: "Enable maintenance mode"
    rollout_strategy: "boolean"
    environments:
      production: false

  rate_limiting:
    enabled: true
    description: "API rate limiting"
    rollout_strategy: "boolean"
    environments:
      production: true
    metadata:
      requests_per_minute: 1000
      burst_limit: 100

# Third-party Integration Flags
integrations:
  github_webhook_v2:
    enabled: false
    description: "Use GitHub webhook v2 format"
    rollout_strategy: "percentage"
    rollout_percentage: 25
    environments:
      staging: true
      production: false

  slack_notifications:
    enabled: true
    description: "Enable Slack notifications for deployments"
    rollout_strategy: "boolean"
    environments:
      staging: true
      production: true

  external_auth_provider:
    enabled: false
    description: "Use external authentication provider"
    rollout_strategy: "user"
    environments:
      development: true
      staging: false
      production: false
    metadata:
      user_list: ["test_user_1", "test_user_2"]

# Deprecated Features (for sunset planning)
deprecated:
  legacy_api_v1:
    enabled: true
    description: "Legacy API v1 endpoints (scheduled for sunset)"
    rollout_strategy: "boolean"
    environments:
      production: true
    metadata:
      sunset_date: "2024-12-31"
      migration_guide: "https://docs.company.com/api-migration"

  old_ui_components:
    enabled: true
    description: "Legacy UI components (being phased out)"
    rollout_strategy: "percentage"
    rollout_percentage: 50
    environments:
      production: true
    metadata:
      replacement: "new_ui_components"
      phase_out_date: "2024-10-31"