# Performance Optimization Thresholds Configuration
# ==================================================
#
# Defines performance thresholds, targets, and alerts for the optimization engine.
# These values are used to guide optimization decisions and trigger performance alerts.

# Global Performance Targets
performance_targets:
  # Primary optimization target - 50% improvement across all metrics
  overall_improvement_percent: 50.0
  
  # File I/O optimization targets
  file_access:
    target_improvement_percent: 50.0
    max_access_time_ms: 100.0
    min_cache_hit_rate_percent: 90.0
    max_memory_usage_mb: 50.0
  
  # AST parsing optimization targets  
  ast_parsing:
    target_improvement_percent: 60.0
    max_parse_time_ms: 500.0
    min_cache_hit_rate_percent: 85.0
    max_memory_usage_mb: 100.0
  
  # Analysis pipeline targets
  analysis_pipeline:
    target_improvement_percent: 45.0
    max_analysis_time_ms: 2000.0
    min_throughput_files_per_second: 10.0
    max_thread_contention_percent: 20.0
  
  # Memory efficiency targets
  memory_optimization:
    target_improvement_percent: 30.0
    max_total_memory_mb: 200.0
    max_growth_rate_mb_per_minute: 10.0
    gc_pressure_threshold: 60  # GC collections per minute

# Cache Performance Thresholds
cache_thresholds:
  # File content cache
  file_cache:
    min_hit_rate_percent: 90.0
    max_memory_usage_mb: 50.0
    max_avg_access_time_ms: 10.0
    eviction_threshold_percent: 80.0
    
  # AST tree cache
  ast_cache:
    min_hit_rate_percent: 85.0
    max_memory_usage_mb: 100.0
    max_avg_parse_time_ms: 50.0
    eviction_threshold_percent: 85.0
    
  # Incremental analysis cache
  incremental_cache:
    min_hit_rate_percent: 80.0
    max_memory_usage_mb: 75.0
    max_delta_processing_time_ms: 25.0
    dependency_invalidation_threshold: 100

# Parallel Processing Thresholds
parallel_processing:
  # Thread pool configuration
  max_workers: 8
  min_workers: 2
  worker_scaling_factor: 1.5
  
  # Performance thresholds
  min_improvement_percent: 20.0
  parallelization_threshold: 5  # Minimum items for parallel processing
  max_memory_per_worker_mb: 50.0
  task_timeout_seconds: 30.0
  
  # Thread contention monitoring
  max_wait_time_ms: 50.0
  max_contention_rate_percent: 25.0
  thread_starvation_threshold_percent: 90.0

# Real-time Monitoring Thresholds
monitoring_thresholds:
  # Alert severity levels
  alerts:
    warning:
      hit_rate_below_percent: 80.0
      memory_usage_above_mb: 150.0
      avg_access_time_above_ms: 50.0
      cpu_usage_above_percent: 75.0
      
    critical:
      hit_rate_below_percent: 70.0
      memory_usage_above_mb: 180.0
      avg_access_time_above_ms: 100.0
      cpu_usage_above_percent: 90.0
      
    emergency:
      hit_rate_below_percent: 50.0
      memory_usage_above_mb: 200.0
      avg_access_time_above_ms: 200.0
      cpu_usage_above_percent: 95.0
  
  # Monitoring intervals
  monitoring_interval_seconds: 30.0
  alert_suppression_duration_seconds: 120.0
  metrics_history_max_entries: 1000
  
  # Performance regression detection
  regression_detection:
    enabled: true
    baseline_window_minutes: 60
    regression_threshold_percent: 15.0
    min_samples_for_baseline: 10

# Cache Warming Configuration
cache_warming:
  # Intelligent warming strategy
  strategy:
    name: "performance_optimization"
    priority_files_limit: 100
    dependency_depth: 3
    parallel_workers: 4
    batch_size: 25
    predictive_prefetch: true
    access_pattern_learning: true
    memory_pressure_threshold: 0.8
  
  # Warming performance targets
  targets:
    max_warming_time_ms: 5000.0
    min_effectiveness_percent: 85.0
    max_memory_usage_mb: 50.0
    predictive_accuracy_target_percent: 75.0

# CI/CD Pipeline Optimization
ci_cd_optimization:
  # Pipeline acceleration targets
  acceleration_targets:
    build_time_reduction_percent: 40.0
    test_execution_reduction_percent: 30.0
    analysis_time_reduction_percent: 50.0
    
  # Batching configuration
  smart_batching:
    enabled: true
    max_batch_size: 50
    timeout_seconds: 300
    failure_retry_count: 2
    
  # Resource limits for CI/CD
  resource_limits:
    max_memory_mb: 500.0
    max_cpu_percent: 80.0
    max_execution_time_minutes: 30

# Performance Regression Detection
regression_detection:
  # Statistical analysis thresholds
  statistical:
    confidence_level: 0.95
    min_sample_size: 20
    outlier_removal_enabled: true
    trend_analysis_window: 100
    
  # Regression alert configuration
  alerts:
    performance_degradation_percent: 15.0
    memory_increase_percent: 25.0
    throughput_decrease_percent: 20.0
    error_rate_increase_percent: 10.0

# Resource Bounds (NASA Rule 7 Compliance)
resource_bounds:
  # Memory limits
  memory:
    max_total_mb: 500.0
    max_cache_mb: 200.0
    max_working_set_mb: 300.0
    emergency_cleanup_threshold_mb: 450.0
    
  # CPU limits  
  cpu:
    max_usage_percent: 85.0
    max_sustained_usage_minutes: 10
    throttling_threshold_percent: 95.0
    
  # File system limits
  filesystem:
    max_open_files: 1000
    max_cache_files: 500
    max_temp_files: 100
    cleanup_interval_minutes: 30
    
  # Network limits (for distributed scenarios)
  network:
    max_connections: 50
    max_bandwidth_mbps: 100.0
    connection_timeout_seconds: 30.0

# Quality Gates for Production
quality_gates:
  # Minimum performance requirements for production deployment
  production_readiness:
    min_overall_improvement_percent: 40.0
    max_memory_usage_mb: 200.0
    min_cache_hit_rate_percent: 85.0
    max_error_rate_percent: 1.0
    min_uptime_percent: 99.0
    
  # Performance consistency requirements
  consistency:
    max_performance_variance_percent: 20.0
    min_reliability_score: 0.95
    max_regression_incidents_per_week: 1

# Environment-specific Overrides
environments:
  development:
    # More relaxed thresholds for development
    performance_targets:
      overall_improvement_percent: 30.0
    resource_bounds:
      memory:
        max_total_mb: 1000.0
        
  testing:
    # Moderate thresholds for testing
    performance_targets:
      overall_improvement_percent: 40.0
    monitoring_thresholds:
      monitoring_interval_seconds: 10.0
      
  production:
    # Strict thresholds for production
    performance_targets:
      overall_improvement_percent: 50.0
    quality_gates:
      production_readiness:
        min_overall_improvement_percent: 45.0
    resource_bounds:
      memory:
        max_total_mb: 300.0

# Optimization Strategies Configuration
optimization_strategies:
  # Cache optimization strategy
  caching:
    enabled: true
    priority: 1
    strategies:
      - intelligent_warming
      - predictive_prefetch
      - adaptive_eviction
      - coherence_management
      
  # Parallel processing strategy
  parallelization:
    enabled: true
    priority: 1
    strategies:
      - thread_pool_optimization
      - task_batching
      - load_balancing
      - resource_scaling
      
  # Memory optimization strategy  
  memory_optimization:
    enabled: true
    priority: 2
    strategies:
      - garbage_collection_tuning
      - object_pooling
      - memory_mapping
      - compression
      
  # I/O optimization strategy
  io_optimization:
    enabled: true  
    priority: 1
    strategies:
      - asynchronous_operations
      - buffering
      - prefetching
      - streaming_processing

# Validation and Testing Configuration
validation:
  # Performance benchmark configuration
  benchmarking:
    enabled: true
    iterations: 10
    warmup_iterations: 3
    statistical_significance: 0.95
    
  # A/B testing for optimization strategies
  ab_testing:
    enabled: false  # Enable for production testing
    control_group_percent: 50.0
    test_duration_hours: 24
    
  # Regression testing
  regression_testing:
    enabled: true
    baseline_retention_days: 30
    automated_rollback: true