# Security Quality Gates Configuration
# Comprehensive security thresholds for production-ready deployment

security_gates:
  # Critical Security Thresholds
  critical_vulnerabilities:
    max_allowed: 0
    blocking: true
    description: "Zero tolerance for critical security vulnerabilities"
    
  high_vulnerabilities:
    max_allowed: 5
    blocking: true
    description: "Maximum high-severity vulnerabilities allowed"
    
  medium_vulnerabilities:
    max_allowed: 20
    blocking: false
    warning_threshold: 15
    description: "Medium-severity vulnerability threshold"
    
  low_vulnerabilities:
    max_allowed: 50
    blocking: false
    description: "Low-severity vulnerability monitoring"

  # Secret Detection
  secrets:
    max_allowed: 0
    blocking: true
    description: "Zero tolerance for secrets in codebase"
    scan_patterns:
      - "API_KEY"
      - "SECRET"
      - "TOKEN"
      - "PASSWORD"
      - "PRIVATE_KEY"
    
  # Dependency Security
  outdated_dependencies:
    max_allowed: 10
    blocking: false
    age_threshold_days: 365
    description: "Maximum outdated dependencies with known vulnerabilities"
    
  # License Compliance
  license_violations:
    max_allowed: 0
    blocking: true
    allowed_licenses:
      - "MIT"
      - "Apache-2.0"
      - "BSD-3-Clause"
      - "ISC"
    description: "Zero tolerance for license violations"

# Tool-Specific Configurations
tools:
  semgrep:
    enabled: true
    ruleset: "owasp-top-10"
    custom_rules_path: "configs/semgrep-rules"
    sarif_output: true
    max_execution_time_minutes: 10
    
  bandit:
    enabled: true
    confidence_level: "medium"
    severity_level: "low"
    format: "json"
    max_execution_time_minutes: 5
    
  safety:
    enabled: true
    ignore_vulnerabilities: []
    max_execution_time_minutes: 3
    
  npm_audit:
    enabled: true
    audit_level: "moderate"
    production_only: false
    max_execution_time_minutes: 5
    
  codeql:
    enabled: true
    languages: ["python", "javascript", "typescript"]
    query_suites: ["security-extended", "security-and-quality"]
    max_execution_time_minutes: 30

# SARIF Integration
sarif:
  enabled: true
  upload_to_github: true
  merge_results: true
  output_directory: ".claude/.artifacts/security/sarif"
  retention_days: 90

# Compliance Frameworks
compliance:
  soc2:
    enabled: true
    controls:
      - "CC6.1"  # Logical Access Security
      - "CC6.7"  # Data Transmission Security
      - "CC6.8"  # Data Classification
    evidence_collection: true
    
  nist:
    enabled: true
    framework: "cybersecurity"
    functions:
      - "identify"
      - "protect"
      - "detect"
      - "respond"
      - "recover"
    
  nasa_pot10:
    enabled: true
    minimum_compliance: 0.92
    rules:
      - "rule_1"  # Control flow
      - "rule_2"  # Function size
      - "rule_3"  # Heap usage
      - "rule_4"  # Loop bounds
      - "rule_5"  # Assertions

# Security Reporting
reporting:
  dashboard_enabled: true
  trend_analysis: true
  risk_scoring: true
  executive_summary: true
  technical_details: true
  
  formats:
    - "json"
    - "html"
    - "pdf"
    - "sarif"
  
  distribution:
    email: false
    slack: false
    github_issues: true
    security_tab: true

# Performance Requirements
performance:
  max_total_execution_time_minutes: 15
  parallel_execution: true
  cache_enabled: true
  cache_ttl_hours: 24
  
  resource_limits:
    max_memory_mb: 2048
    max_cpu_cores: 4
    max_disk_space_mb: 1024

# Emergency Protocols
emergency:
  critical_vulnerability_response:
    auto_create_issue: true
    block_deployment: true
    notify_security_team: true
    
  secret_detection_response:
    auto_revoke: false
    create_incident: true
    block_deployment: true
    
  compliance_failure_response:
    grace_period_hours: 24
    escalation_enabled: true
    auto_remediation: false

# Integration Settings
integrations:
  github_security:
    enabled: true
    create_security_advisories: true
    dependency_updates: true
    
  jira_security:
    enabled: false
    project_key: "SECURITY"
    
  slack_security:
    enabled: false
    channel: "#security-alerts"

# Quality Metrics
metrics:
  security_debt_tracking: true
  mean_time_to_remediation: true
  vulnerability_introduction_rate: true
  security_coverage_percentage: true
  false_positive_rate: true