# NIST Cybersecurity Framework Implementation
# Comprehensive cybersecurity controls for defense industry compliance

nist_framework:
  version: "1.1"
  implementation_tier: "tier_3"  # Repeatable (Target: Tier 4 - Adaptive)
  
  # IDENTIFY Function (ID)
  identify:
    id_am_1:
      name: "Asset Management - Physical devices and systems"
      description: "Physical devices and systems within the organization are inventoried"
      controls:
        - "Maintain comprehensive asset inventory"
        - "Classify assets by criticality and sensitivity"
        - "Track asset ownership and lifecycle"
      implementation:
        automated_discovery: true
        asset_database: ".claude/.artifacts/compliance/nist/asset_inventory.json"
        update_frequency: "daily"
        
    id_am_2:
      name: "Asset Management - Software platforms and applications"
      description: "Software platforms and applications within the organization are inventoried"
      controls:
        - "Software asset inventory management"
        - "License compliance tracking"
        - "Version management and patching"
      implementation:
        dependency_scanning: true
        tools: ["safety", "npm_audit", "pip-audit"]
        sbom_generation: true
        
    id_be_5:
      name: "Business Environment - Resilience requirements"
      description: "Resilience requirements to support delivery of critical services are established"
      controls:
        - "Critical service identification"
        - "Recovery time objectives (RTO)"
        - "Recovery point objectives (RPO)"
      implementation:
        disaster_recovery_plan: true
        business_continuity_testing: "quarterly"
        
    id_gv_1:
      name: "Governance - Cybersecurity policy"
      description: "Organizational cybersecurity policy is established and communicated"
      controls:
        - "Security policy documentation"
        - "Policy communication and training"
        - "Regular policy reviews and updates"
      implementation:
        policy_location: "docs/compliance/security_policy.md"
        review_frequency: "annual"
        
    id_ra_1:
      name: "Risk Assessment - Asset vulnerabilities"
      description: "Asset vulnerabilities are identified and documented"
      controls:
        - "Vulnerability scanning and assessment"
        - "Risk scoring and prioritization"
        - "Vulnerability remediation tracking"
      implementation:
        scanning_tools: ["semgrep", "bandit", "codeql"]
        scan_frequency: "daily"
        risk_scoring: "cvss_v3"

  # PROTECT Function (PR)
  protect:
    pr_ac_1:
      name: "Access Control - Identity and credential management"
      description: "Identities and credentials are issued, managed, verified, revoked, and audited"
      controls:
        - "Identity lifecycle management"
        - "Credential security requirements"
        - "Multi-factor authentication"
      implementation:
        identity_provider: "enterprise_sso"
        mfa_enforcement: true
        credential_rotation: "90_days"
        
    pr_ac_3:
      name: "Access Control - Remote access"
      description: "Remote access is managed"
      controls:
        - "Secure remote access protocols"
        - "VPN configuration and monitoring"
        - "Remote session logging"
      implementation:
        vpn_required: true
        session_monitoring: true
        access_logging: "comprehensive"
        
    pr_ac_4:
      name: "Access Control - Permissions and authorizations"
      description: "Access permissions and authorizations are managed"
      controls:
        - "Least privilege implementation"
        - "Role-based access control (RBAC)"
        - "Regular access reviews"
      implementation:
        rbac_implementation: true
        access_review_frequency: "quarterly"
        privilege_escalation_monitoring: true
        
    pr_ds_1:
      name: "Data Security - Data-at-rest protection"
      description: "Data-at-rest is protected"
      controls:
        - "Encryption of sensitive data at rest"
        - "Secure key management"
        - "Database security controls"
      implementation:
        encryption_algorithm: "AES-256"
        key_management: "hardware_security_module"
        database_encryption: true
        
    pr_ds_2:
      name: "Data Security - Data-in-transit protection"
      description: "Data-in-transit is protected"
      controls:
        - "Encryption of data in transit"
        - "Secure communication protocols"
        - "Certificate management"
      implementation:
        tls_version: "1.3"
        certificate_validation: true
        secure_protocols_only: true
        
    pr_ip_1:
      name: "Information Protection - Baseline configuration"
      description: "A baseline configuration of information technology/industrial control systems is created and maintained"
      controls:
        - "Security configuration standards"
        - "Configuration management"
        - "Hardening guidelines"
      implementation:
        configuration_as_code: true
        baseline_enforcement: true
        drift_detection: true
        
    pr_pt_1:
      name: "Protective Technology - Audit logs"
      description: "Audit/log records are determined, documented, implemented, and reviewed"
      controls:
        - "Comprehensive logging strategy"
        - "Log retention and archival"
        - "Log analysis and monitoring"
      implementation:
        centralized_logging: true
        log_retention_days: 365
        real_time_analysis: true

  # DETECT Function (DE)
  detect:
    de_ae_1:
      name: "Anomalies and Events - Baseline establishment"
      description: "A baseline of network operations and expected data flows is established"
      controls:
        - "Network traffic baseline"
        - "Application behavior baseline"
        - "User activity patterns"
      implementation:
        behavioral_analysis: true
        ml_anomaly_detection: true
        baseline_update_frequency: "monthly"
        
    de_ae_2:
      name: "Anomalies and Events - Detected events analysis"
      description: "Detected events are analyzed to understand attack targets and methods"
      controls:
        - "Event correlation and analysis"
        - "Threat intelligence integration"
        - "Attack pattern recognition"
      implementation:
        siem_integration: true
        threat_intel_feeds: true
        automated_analysis: true
        
    de_cm_1:
      name: "Continuous Monitoring - Network monitoring"
      description: "The network is monitored to detect potential cybersecurity events"
      controls:
        - "Network traffic monitoring"
        - "Intrusion detection systems"
        - "Network segmentation monitoring"
      implementation:
        network_monitoring: true
        ids_deployment: true
        traffic_analysis: "deep_packet_inspection"
        
    de_cm_7:
      name: "Continuous Monitoring - Personnel activity"
      description: "Personnel activity is monitored to detect potential cybersecurity events"
      controls:
        - "User activity monitoring"
        - "Privileged account monitoring"
        - "Insider threat detection"
      implementation:
        user_behavior_analytics: true
        privileged_session_recording: true
        insider_threat_program: true

  # RESPOND Function (RS)
  respond:
    rs_rp_1:
      name: "Response Planning - Response plan"
      description: "Response plan is executed during or after an incident"
      controls:
        - "Incident response plan"
        - "Response team roles and responsibilities"
        - "Communication procedures"
      implementation:
        incident_response_plan: "docs/compliance/incident_response_plan.md"
        response_team: "designated"
        escalation_procedures: true
        
    rs_co_2:
      name: "Communications - Stakeholder notifications"
      description: "Incidents are reported consistent with established criteria"
      controls:
        - "Incident reporting criteria"
        - "Stakeholder notification procedures"
        - "External reporting requirements"
      implementation:
        automated_notifications: true
        stakeholder_matrix: "defined"
        regulatory_reporting: "compliant"
        
    rs_an_1:
      name: "Analysis - Impact assessment"
      description: "Notifications from detection systems are investigated"
      controls:
        - "Alert investigation procedures"
        - "Impact assessment methodology"
        - "Evidence collection and preservation"
      implementation:
        investigation_playbooks: true
        forensic_capabilities: true
        evidence_preservation: "chain_of_custody"

  # RECOVER Function (RC)
  recover:
    rc_rp_1:
      name: "Recovery Planning - Recovery plan"
      description: "Recovery plan is executed during or after a cybersecurity incident"
      controls:
        - "Recovery procedures"
        - "System restoration priorities"
        - "Business continuity integration"
      implementation:
        recovery_procedures: "documented"
        restoration_priorities: "defined"
        rto_compliance: true
        
    rc_im_1:
      name: "Improvements - Response incorporation"
      description: "Recovery planning and processes are improved"
      controls:
        - "Lessons learned integration"
        - "Process improvement procedures"
        - "Recovery testing and exercises"
      implementation:
        post_incident_reviews: true
        process_improvements: "tracked"
        recovery_testing: "quarterly"

# Implementation Roadmap
implementation_roadmap:
  current_state: "tier_2_risk_informed"
  target_state: "tier_3_repeatable"
  timeline: "12_months"
  
  phases:
    phase_1_foundation:
      duration: "3_months"
      objectives:
        - "Complete asset inventory"
        - "Establish baseline configurations"
        - "Implement core access controls"
      deliverables:
        - "Asset management database"
        - "Security configuration standards"
        - "Identity and access management system"
        
    phase_2_detection:
      duration: "3_months"
      objectives:
        - "Deploy monitoring solutions"
        - "Establish security operations center"
        - "Implement incident response procedures"
      deliverables:
        - "SIEM deployment"
        - "SOC procedures"
        - "Incident response playbooks"
        
    phase_3_automation:
      duration: "3_months"
      objectives:
        - "Automate security processes"
        - "Implement continuous monitoring"
        - "Deploy security orchestration"
      deliverables:
        - "Security automation platform"
        - "Continuous monitoring dashboards"
        - "Orchestrated response capabilities"
        
    phase_4_optimization:
      duration: "3_months"
      objectives:
        - "Optimize security operations"
        - "Implement advanced analytics"
        - "Achieve tier 3 maturity"
      deliverables:
        - "Optimized security processes"
        - "Advanced threat detection"
        - "Maturity assessment report"

# Metrics and Measurement
metrics:
  effectiveness_measures:
    identify:
      - "asset_inventory_completeness"
      - "vulnerability_identification_rate"
      - "risk_assessment_coverage"
      
    protect:
      - "access_control_effectiveness"
      - "data_protection_compliance"
      - "security_training_completion"
      
    detect:
      - "mean_time_to_detection"
      - "false_positive_rate"
      - "security_event_correlation_rate"
      
    respond:
      - "mean_time_to_response"
      - "incident_containment_time"
      - "stakeholder_notification_timeliness"
      
    recover:
      - "mean_time_to_recovery"
      - "business_service_restoration_time"
      - "lessons_learned_implementation_rate"

# Compliance Evidence Collection
evidence_collection:
  automated_collection:
    - "Security scan results"
    - "Configuration compliance reports"
    - "Access control audit logs"
    - "Vulnerability management reports"
    
  periodic_assessments:
    - "Control effectiveness testing"
    - "Security awareness assessments"
    - "Business continuity exercises"
    - "Penetration testing results"
    
  documentation_requirements:
    - "Policy and procedure documentation"
    - "Risk assessment reports"
    - "Incident response documentation"
    - "Security training records"

# Integration with Security Tools
tool_mapping:
  identify:
    asset_discovery: ["nmap", "asset_inventory_tools"]
    vulnerability_scanning: ["semgrep", "bandit", "safety", "codeql"]
    risk_assessment: ["security_validator", "risk_calculator"]
    
  protect:
    access_control: ["iam_systems", "rbac_tools"]
    data_protection: ["encryption_tools", "dlp_solutions"]
    security_training: ["awareness_platforms"]
    
  detect:
    monitoring: ["siem", "log_analysis_tools"]
    anomaly_detection: ["ml_detection", "behavior_analytics"]
    threat_intelligence: ["threat_feeds", "ioc_platforms"]
    
  respond:
    incident_management: ["incident_response_platform"]
    forensics: ["forensic_tools", "evidence_collection"]
    communication: ["notification_systems"]
    
  recover:
    backup_restoration: ["backup_systems", "disaster_recovery"]
    business_continuity: ["bc_tools", "communication_systems"]