# SOC 2 Type II Compliance Controls Configuration
# Security framework alignment for defense industry readiness

soc2_controls:
  # Trust Service Category: Security (CC)
  cc6_1:
    name: "Logical and Physical Access Controls"
    description: "Controls provide reasonable assurance that access to information and system resources is restricted to authorized users"
    requirements:
      - "Multi-factor authentication for all administrative access"
      - "Role-based access control (RBAC) implementation"
      - "Regular access reviews and deprovisioning"
      - "Privileged access management (PAM)"
    evidence_collection:
      - "Access control policies and procedures"
      - "User access reports and reviews"
      - "Authentication logs and monitoring"
      - "Privileged access session recordings"
    automated_controls:
      - "Semgrep authentication pattern scanning"
      - "Bandit access control vulnerability detection"
      - "CodeQL privilege escalation analysis"
    
  cc6_2:
    name: "Logical and Physical Access Controls - Transmission"
    description: "Information is protected during transmission and disposal"
    requirements:
      - "Encryption in transit (TLS 1.2+ minimum)"
      - "Secure communication protocols"
      - "Data loss prevention (DLP)"
      - "Secure disposal procedures"
    evidence_collection:
      - "Encryption standards and implementation"
      - "Network security configurations"
      - "Data transmission logs"
      - "Disposal certificates and procedures"
    automated_controls:
      - "TLS configuration scanning"
      - "Weak cryptography detection"
      - "Insecure transmission pattern analysis"
    
  cc6_3:
    name: "Logical and Physical Access Controls - Access Management"
    description: "Access to data, software, functions, and other system resources is restricted"
    requirements:
      - "Least privilege principle enforcement"
      - "Segregation of duties"
      - "Regular access certification"
      - "Automated access provisioning and deprovisioning"
    evidence_collection:
      - "Access control matrices"
      - "Segregation of duties analysis"
      - "Access certification reports"
      - "Automated provisioning logs"
    automated_controls:
      - "Excessive privilege detection"
      - "Authorization bypass vulnerability scanning"
      - "Access control policy compliance checking"

  cc6_7:
    name: "System Operations - Data Transmission"
    description: "Transmission of data and information is authorized and complete"
    requirements:
      - "Message integrity validation"
      - "Secure data transmission channels"
      - "Authorized data sharing protocols"
      - "Transmission monitoring and logging"
    evidence_collection:
      - "Data transmission policies"
      - "Integrity validation procedures" 
      - "Secure channel configurations"
      - "Transmission audit logs"
    automated_controls:
      - "Data integrity vulnerability scanning"
      - "Insecure transmission detection"
      - "Message tampering analysis"

  cc6_8:
    name: "System Operations - Data Classification"
    description: "Data is classified and handled according to its classification"
    requirements:
      - "Data classification policy"
      - "Handling procedures by classification"
      - "Data labeling and marking"
      - "Classification-based access controls"
    evidence_collection:
      - "Data classification policy documentation"
      - "Data handling procedures"
      - "Classification implementation evidence"
      - "Access control by classification reports"
    automated_controls:
      - "Sensitive data detection"
      - "Data classification policy violations"
      - "Inappropriate data access patterns"

# Compliance Monitoring Configuration
monitoring:
  control_testing_frequency: "quarterly"
  evidence_collection_automation: true
  continuous_monitoring: true
  
  automated_testing:
    security_scanning:
      frequency: "daily"
      tools: ["semgrep", "bandit", "safety", "codeql"]
      
    access_control_testing:
      frequency: "weekly" 
      tests:
        - "privileged access validation"
        - "authentication bypass testing"
        - "authorization policy compliance"
        
    data_protection_testing:
      frequency: "daily"
      tests:
        - "encryption implementation validation"
        - "data transmission security"
        - "sensitive data exposure detection"

# Evidence Collection Framework
evidence_framework:
  collection_methods:
    automated:
      - "Security scan results and artifacts"
      - "Access control system logs"
      - "Audit trail collection"
      - "Configuration compliance reports"
      
    manual:
      - "Policy documentation reviews"
      - "Process walkthroughs"
      - "Control design assessments"
      - "Incident response testing"
  
  storage:
    location: ".claude/.artifacts/compliance/soc2"
    retention_period: "7_years"
    encryption: "AES-256"
    access_controls: "role_based"
    
  reporting:
    formats: ["json", "pdf", "csv"]
    frequency: "monthly"
    distribution:
      - "compliance_team"
      - "security_team"
      - "executive_leadership"

# Integration with Security Tools
security_tool_mapping:
  semgrep:
    relevant_controls: ["cc6_1", "cc6_2", "cc6_3", "cc6_7"]
    evidence_types:
      - "access_control_vulnerabilities"
      - "authentication_weaknesses"
      - "authorization_bypasses"
      - "data_transmission_issues"
      
  bandit:
    relevant_controls: ["cc6_1", "cc6_2", "cc6_8"]
    evidence_types:
      - "python_security_vulnerabilities"
      - "hardcoded_credentials"
      - "insecure_cryptography"
      
  codeql:
    relevant_controls: ["cc6_1", "cc6_2", "cc6_3", "cc6_7", "cc6_8"]
    evidence_types:
      - "advanced_security_analysis"
      - "data_flow_analysis"
      - "authentication_vulnerabilities"
      - "authorization_issues"

# Risk Assessment Framework
risk_assessment:
  control_risk_factors:
    cc6_1:
      inherent_risk: "high"
      residual_risk: "medium"
      risk_factors:
        - "privileged_access_complexity"
        - "multi_factor_auth_coverage"
        - "access_review_completeness"
        
    cc6_2:
      inherent_risk: "high"
      residual_risk: "low"
      risk_factors:
        - "encryption_strength"
        - "protocol_security"
        - "transmission_monitoring"
        
    cc6_3:
      inherent_risk: "medium"
      residual_risk: "low"
      risk_factors:
        - "least_privilege_implementation"
        - "segregation_effectiveness"
        - "access_certification_coverage"

# Compliance Metrics and KPIs
metrics:
  control_effectiveness:
    measurement_criteria:
      - "automated_test_pass_rate"
      - "security_finding_remediation_time"
      - "access_review_completion_rate"
      - "incident_response_time"
      
  target_thresholds:
    security_scan_pass_rate: 95
    critical_finding_resolution_days: 3
    high_finding_resolution_days: 7
    access_review_completion_percentage: 100
    
  reporting_metrics:
    - "control_testing_results"
    - "evidence_collection_completeness"
    - "security_posture_trends"
    - "compliance_gap_analysis"