apiVersion: v2
name: gary-taleb-trading
description: A Helm chart for Gary×Taleb Trading System - Defense Industry Ready
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/gary-taleb-trading/system
sources:
  - https://github.com/gary-taleb-trading/system
keywords:
  - trading
  - financial
  - high-frequency
  - gary
  - taleb
  - defense-industry
maintainers:
  - name: DevOps Team
    email: devops@gary-taleb.trading
annotations:
  category: Trading Systems
  licenses: Apache-2.0

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 15.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled